pipeline {
    agent any

    environment {
        EC2_HOST = 'ubuntu@13.217.224.102'
        APP_PORT = '8000'
    }

    stages {
        stage('Checkout') {
            steps {
                git credentialsId: 'github-cred', url: 'https://github.com/Ramezz07/jvlcart.git'
            }
        }

        stage('Copy Code to EC2') {
            steps {
                sshagent(['sshkey-cred']) {
                    sh '''
                        rsync -avz \
                            --exclude='node_modules' \
                            --exclude='.git' \
                            --exclude='frontend' \
                            ./backend/ ${EC2_HOST}:/home/ubuntu/app/
                    '''
                }
            }
        }

        stage('Build Docker Image on EC2') {
            steps {
                sshagent(['sshkey-cred']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ${EC2_HOST} "
                            cd /home/ubuntu/app
                            docker build -t jvlcart-backend:latest .
                        "
                    '''
                }
            }
        }

        stage('Run Docker Container on EC2') {
            steps {
                sshagent(['sshkey-cred']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no ${EC2_HOST} "
                            docker stop jvlcart-backend || true
                            docker rm jvlcart-backend || true

                            docker run -d \
                                --name jvlcart-backend \
                                -p ${APP_PORT}:${APP_PORT} \
                                --env-file /home/ubuntu/app/config/config.env \
                                --restart always \
                                jvlcart-backend:latest
                        "
                    '''
                }
            }
        }
    }
}
